services:
  api-gateway:
    image: nginx
    volumes:
      - type: bind
        source: ./api-gateway/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8090:80
    develop:
      watch:
        - action: restart
          path: ./api-gateway/nginx.conf
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./user-service/
    depends_on:
      - mongo

  mongo:
    image: mongo