services:
  api-gateway:
    image: nginx
    volumes:
      - type: bind
        source: ./api-gateway/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8090:80
    develop:
      watch:
        - action: restart
          path: ./api-gateway/nginx.conf
    depends_on:
      - user-service
      - order-service

  user-service:
    build: ./user-service
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./user-service/
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://mongo:27017"
  
  order-service:
    build: ./order-service
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./order-service/
    depends_on:
      - mongo
    
    environment:
      DATABASE_URL: "mongodb://mongo:27017"

  web-ui:
    build: ./web-ui
    restart: unless-stopped
    ports:
      - 8091:80
    depends_on:
      - api-gateway
    develop:
      watch:
        - action: rebuild
          path: ./web-ui

  mongo:
    image: mongo