services:
  api-gateway:
    image: nginx
    volumes:
      - type: bind
        source: ./api-gateway/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8090:80
    develop:
      watch:
        - action: restart
          path: ./api-gateway/nginx.conf
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./user-service/
    secrets:
      - jwt_private_key
    depends_on:
      - mongo

  web-ui:
    build: ./web-ui
    restart: unless-stopped
    ports:
      - 8091:80
    depends_on:
      - api-gateway
    develop:
      watch:
        - action: rebuild
          path: ./web-ui

  mongo:
    image: mongo

secrets:
  jwt_key:
    file: ./service.pub.key
  
  jwt_private_key:
    file: ./service.priv.key
  