apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:local
          envFrom:
              - configMapRef:
                  name: env-map

          ports:
          - containerPort: 5000
          - containerPort: 5001
---


apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: grpc
    port: 5001
    targetPort: 5001
  selector:
    app: payment-service
  type: ClusterIP
