apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: review-service:local
          envFrom:
              - configMapRef:
                  name: env-map
          env:
              - name: APP_SECRET_jwt_key
                valueFrom:
                  secretKeyRef:
                    name: jwt-key
                    key: jwt_key
          ports:
          - containerPort: 5000
          - containerPort: 5001
---


apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: grpc
    port: 5001
    targetPort: 5001
  selector:
    app: review-service
  type: ClusterIP
