apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
        - name: web-ui
          image: web-ui:local
          envFrom:
              - configMapRef:
                  name: env-map
          ports:
          - containerPort: 5000
          - containerPort: 5001
---


apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: web-ui
  type: LoadBalancer
