// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: restaurent-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemIdList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        []string               `protobuf:"bytes,1,rep,name=itemId,proto3" json:"itemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemIdList) Reset() {
	*x = ItemIdList{}
	mi := &file_restaurent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemIdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemIdList) ProtoMessage() {}

func (x *ItemIdList) ProtoReflect() protoreflect.Message {
	mi := &file_restaurent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemIdList.ProtoReflect.Descriptor instead.
func (*ItemIdList) Descriptor() ([]byte, []int) {
	return file_restaurent_service_proto_rawDescGZIP(), []int{0}
}

func (x *ItemIdList) GetItemId() []string {
	if x != nil {
		return x.ItemId
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	RestaurentId  string                 `protobuf:"bytes,2,opt,name=restaurentId,proto3" json:"restaurentId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_restaurent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_restaurent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_restaurent_service_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Item) GetRestaurentId() string {
	if x != nil {
		return x.RestaurentId
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*Item                `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemList) Reset() {
	*x = ItemList{}
	mi := &file_restaurent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemList) ProtoMessage() {}

func (x *ItemList) ProtoReflect() protoreflect.Message {
	mi := &file_restaurent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemList.ProtoReflect.Descriptor instead.
func (*ItemList) Descriptor() ([]byte, []int) {
	return file_restaurent_service_proto_rawDescGZIP(), []int{2}
}

func (x *ItemList) GetItem() []*Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type RestaurentId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurentId  string                 `protobuf:"bytes,1,opt,name=restaurentId,proto3" json:"restaurentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurentId) Reset() {
	*x = RestaurentId{}
	mi := &file_restaurent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurentId) ProtoMessage() {}

func (x *RestaurentId) ProtoReflect() protoreflect.Message {
	mi := &file_restaurent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurentId.ProtoReflect.Descriptor instead.
func (*RestaurentId) Descriptor() ([]byte, []int) {
	return file_restaurent_service_proto_rawDescGZIP(), []int{3}
}

func (x *RestaurentId) GetRestaurentId() string {
	if x != nil {
		return x.RestaurentId
	}
	return ""
}

type Restaurent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurentId  string                 `protobuf:"bytes,1,opt,name=restaurentId,proto3" json:"restaurentId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurent) Reset() {
	*x = Restaurent{}
	mi := &file_restaurent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurent) ProtoMessage() {}

func (x *Restaurent) ProtoReflect() protoreflect.Message {
	mi := &file_restaurent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurent.ProtoReflect.Descriptor instead.
func (*Restaurent) Descriptor() ([]byte, []int) {
	return file_restaurent_service_proto_rawDescGZIP(), []int{4}
}

func (x *Restaurent) GetRestaurentId() string {
	if x != nil {
		return x.RestaurentId
	}
	return ""
}

func (x *Restaurent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurent) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

var File_restaurent_service_proto protoreflect.FileDescriptor

const file_restaurent_service_proto_rawDesc = "" +
	"\n" +
	"\x18restaurent-service.proto\"$\n" +
	"\n" +
	"ItemIdList\x12\x16\n" +
	"\x06itemId\x18\x01 \x03(\tR\x06itemId\"\x8e\x01\n" +
	"\x04Item\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\"\n" +
	"\frestaurentId\x18\x02 \x01(\tR\frestaurentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"%\n" +
	"\bItemList\x12\x19\n" +
	"\x04item\x18\x01 \x03(\v2\x05.ItemR\x04item\"2\n" +
	"\fRestaurentId\x12\"\n" +
	"\frestaurentId\x18\x01 \x01(\tR\frestaurentId\"^\n" +
	"\n" +
	"Restaurent\x12\"\n" +
	"\frestaurentId\x18\x01 \x01(\tR\frestaurentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aownerId\x18\x03 \x01(\tR\aownerId2p\n" +
	"\x11RestaurentService\x12(\n" +
	"\fGetItemsById\x12\v.ItemIdList\x1a\t.ItemList\"\x00\x121\n" +
	"\x11GetRestaurentById\x12\r.RestaurentId\x1a\v.Restaurent\"\x00B\tZ\a./protob\x06proto3"

var (
	file_restaurent_service_proto_rawDescOnce sync.Once
	file_restaurent_service_proto_rawDescData []byte
)

func file_restaurent_service_proto_rawDescGZIP() []byte {
	file_restaurent_service_proto_rawDescOnce.Do(func() {
		file_restaurent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurent_service_proto_rawDesc), len(file_restaurent_service_proto_rawDesc)))
	})
	return file_restaurent_service_proto_rawDescData
}

var file_restaurent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_restaurent_service_proto_goTypes = []any{
	(*ItemIdList)(nil),   // 0: ItemIdList
	(*Item)(nil),         // 1: Item
	(*ItemList)(nil),     // 2: ItemList
	(*RestaurentId)(nil), // 3: RestaurentId
	(*Restaurent)(nil),   // 4: Restaurent
}
var file_restaurent_service_proto_depIdxs = []int32{
	1, // 0: ItemList.item:type_name -> Item
	0, // 1: RestaurentService.GetItemsById:input_type -> ItemIdList
	3, // 2: RestaurentService.GetRestaurentById:input_type -> RestaurentId
	2, // 3: RestaurentService.GetItemsById:output_type -> ItemList
	4, // 4: RestaurentService.GetRestaurentById:output_type -> Restaurent
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_restaurent_service_proto_init() }
func file_restaurent_service_proto_init() {
	if File_restaurent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurent_service_proto_rawDesc), len(file_restaurent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurent_service_proto_goTypes,
		DependencyIndexes: file_restaurent_service_proto_depIdxs,
		MessageInfos:      file_restaurent_service_proto_msgTypes,
	}.Build()
	File_restaurent_service_proto = out.File
	file_restaurent_service_proto_goTypes = nil
	file_restaurent_service_proto_depIdxs = nil
}
