// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RestaurentServiceClient is the client API for RestaurentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurentServiceClient interface {
	// Gets the items
	GetItemsById(ctx context.Context, in *ItemIdList, opts ...grpc.CallOption) (*ItemList, error)
	GetRestaurentById(ctx context.Context, in *RestaurentId, opts ...grpc.CallOption) (*Restaurent, error)
}

type restaurentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurentServiceClient(cc grpc.ClientConnInterface) RestaurentServiceClient {
	return &restaurentServiceClient{cc}
}

func (c *restaurentServiceClient) GetItemsById(ctx context.Context, in *ItemIdList, opts ...grpc.CallOption) (*ItemList, error) {
	out := new(ItemList)
	err := c.cc.Invoke(ctx, "/RestaurentService/GetItemsById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurentServiceClient) GetRestaurentById(ctx context.Context, in *RestaurentId, opts ...grpc.CallOption) (*Restaurent, error) {
	out := new(Restaurent)
	err := c.cc.Invoke(ctx, "/RestaurentService/GetRestaurentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurentServiceServer is the server API for RestaurentService service.
// All implementations must embed UnimplementedRestaurentServiceServer
// for forward compatibility
type RestaurentServiceServer interface {
	// Gets the items
	GetItemsById(context.Context, *ItemIdList) (*ItemList, error)
	GetRestaurentById(context.Context, *RestaurentId) (*Restaurent, error)
	mustEmbedUnimplementedRestaurentServiceServer()
}

// UnimplementedRestaurentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRestaurentServiceServer struct {
}

func (UnimplementedRestaurentServiceServer) GetItemsById(context.Context, *ItemIdList) (*ItemList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemsById not implemented")
}
func (UnimplementedRestaurentServiceServer) GetRestaurentById(context.Context, *RestaurentId) (*Restaurent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurentById not implemented")
}
func (UnimplementedRestaurentServiceServer) mustEmbedUnimplementedRestaurentServiceServer() {}

// UnsafeRestaurentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurentServiceServer will
// result in compilation errors.
type UnsafeRestaurentServiceServer interface {
	mustEmbedUnimplementedRestaurentServiceServer()
}

func RegisterRestaurentServiceServer(s *grpc.Server, srv RestaurentServiceServer) {
	s.RegisterService(&_RestaurentService_serviceDesc, srv)
}

func _RestaurentService_GetItemsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemIdList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurentServiceServer).GetItemsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RestaurentService/GetItemsById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurentServiceServer).GetItemsById(ctx, req.(*ItemIdList))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurentService_GetRestaurentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestaurentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurentServiceServer).GetRestaurentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RestaurentService/GetRestaurentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurentServiceServer).GetRestaurentById(ctx, req.(*RestaurentId))
	}
	return interceptor(ctx, in, info, handler)
}

var _RestaurentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RestaurentService",
	HandlerType: (*RestaurentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemsById",
			Handler:    _RestaurentService_GetItemsById_Handler,
		},
		{
			MethodName: "GetRestaurentById",
			Handler:    _RestaurentService_GetRestaurentById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restaurent-service.proto",
}
