// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: delivery-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderId) Reset() {
	*x = OrderId{}
	mi := &file_delivery_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderId) ProtoMessage() {}

func (x *OrderId) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderId.ProtoReflect.Descriptor instead.
func (*OrderId) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{0}
}

func (x *OrderId) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Delivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DiverId       string                 `protobuf:"bytes,3,opt,name=diverId,proto3" json:"diverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_delivery_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{1}
}

func (x *Delivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Delivery) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Delivery) GetDiverId() string {
	if x != nil {
		return x.DiverId
	}
	return ""
}

type DeliverId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliverId     string                 `protobuf:"bytes,1,opt,name=deliverId,proto3" json:"deliverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverId) Reset() {
	*x = DeliverId{}
	mi := &file_delivery_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverId) ProtoMessage() {}

func (x *DeliverId) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverId.ProtoReflect.Descriptor instead.
func (*DeliverId) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverId) GetDeliverId() string {
	if x != nil {
		return x.DeliverId
	}
	return ""
}

type DeliveryDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Destination   *DeliveryAddress       `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Pickup        *DeliveryRestaurant    `protobuf:"bytes,3,opt,name=pickup,proto3" json:"pickup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryDetails) Reset() {
	*x = DeliveryDetails{}
	mi := &file_delivery_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryDetails) ProtoMessage() {}

func (x *DeliveryDetails) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryDetails.ProtoReflect.Descriptor instead.
func (*DeliveryDetails) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryDetails) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeliveryDetails) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeliveryDetails) GetDestination() *DeliveryAddress {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *DeliveryDetails) GetPickup() *DeliveryRestaurant {
	if x != nil {
		return x.Pickup
	}
	return nil
}

type DeliveryAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            string                 `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	Town          string                 `protobuf:"bytes,3,opt,name=town,proto3" json:"town,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Position      *DeliveryLocation      `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAddress) Reset() {
	*x = DeliveryAddress{}
	mi := &file_delivery_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAddress) ProtoMessage() {}

func (x *DeliveryAddress) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAddress.ProtoReflect.Descriptor instead.
func (*DeliveryAddress) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryAddress) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *DeliveryAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *DeliveryAddress) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *DeliveryAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DeliveryAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *DeliveryAddress) GetPosition() *DeliveryLocation {
	if x != nil {
		return x.Position
	}
	return nil
}

type DeliveryRestaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Location      *DeliveryLocation      `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryRestaurant) Reset() {
	*x = DeliveryRestaurant{}
	mi := &file_delivery_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryRestaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRestaurant) ProtoMessage() {}

func (x *DeliveryRestaurant) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRestaurant.ProtoReflect.Descriptor instead.
func (*DeliveryRestaurant) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryRestaurant) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *DeliveryRestaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeliveryRestaurant) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DeliveryRestaurant) GetLocation() *DeliveryLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type DeliveryLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryLocation) Reset() {
	*x = DeliveryLocation{}
	mi := &file_delivery_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryLocation) ProtoMessage() {}

func (x *DeliveryLocation) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryLocation.ProtoReflect.Descriptor instead.
func (*DeliveryLocation) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DeliveryLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

var File_delivery_service_proto protoreflect.FileDescriptor

const file_delivery_service_proto_rawDesc = "" +
	"\n" +
	"\x16delivery-service.proto\"#\n" +
	"\aOrderId\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\"\\\n" +
	"\bDelivery\x12\x1e\n" +
	"\n" +
	"deliveryId\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\adiverId\x18\x03 \x01(\tR\adiverId\")\n" +
	"\tDeliverId\x12\x1c\n" +
	"\tdeliverId\x18\x01 \x01(\tR\tdeliverId\"\xa4\x01\n" +
	"\x0fDeliveryDetails\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\x122\n" +
	"\vdestination\x18\x02 \x01(\v2\x10.DeliveryAddressR\vdestination\x12+\n" +
	"\x06pickup\x18\x03 \x01(\v2\x13.DeliveryRestaurantR\x06pickup\"\xb0\x01\n" +
	"\x0fDeliveryAddress\x12\x0e\n" +
	"\x02no\x18\x01 \x01(\tR\x02no\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x12\n" +
	"\x04town\x18\x03 \x01(\tR\x04town\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\x05 \x01(\tR\n" +
	"postalCode\x12-\n" +
	"\bposition\x18\x06 \x01(\v2\x11.DeliveryLocationR\bposition\"\x95\x01\n" +
	"\x12DeliveryRestaurant\x12\"\n" +
	"\frestaurantId\x18\x01 \x01(\tR\frestaurantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aownerId\x18\x03 \x01(\tR\aownerId\x12-\n" +
	"\blocation\x18\x04 \x01(\v2\x11.DeliveryLocationR\blocation\"L\n" +
	"\x10DeliveryLocation\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude2o\n" +
	"\x0fDeliveryService\x12-\n" +
	"\vAddDelivery\x12\x10.DeliveryDetails\x1a\n" +
	".DeliverId\"\x00\x12-\n" +
	"\x14GetDeliveryByOrderId\x12\b.OrderId\x1a\t.Delivery\"\x00B\tZ\a./protob\x06proto3"

var (
	file_delivery_service_proto_rawDescOnce sync.Once
	file_delivery_service_proto_rawDescData []byte
)

func file_delivery_service_proto_rawDescGZIP() []byte {
	file_delivery_service_proto_rawDescOnce.Do(func() {
		file_delivery_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_service_proto_rawDesc), len(file_delivery_service_proto_rawDesc)))
	})
	return file_delivery_service_proto_rawDescData
}

var file_delivery_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_delivery_service_proto_goTypes = []any{
	(*OrderId)(nil),            // 0: OrderId
	(*Delivery)(nil),           // 1: Delivery
	(*DeliverId)(nil),          // 2: DeliverId
	(*DeliveryDetails)(nil),    // 3: DeliveryDetails
	(*DeliveryAddress)(nil),    // 4: DeliveryAddress
	(*DeliveryRestaurant)(nil), // 5: DeliveryRestaurant
	(*DeliveryLocation)(nil),   // 6: DeliveryLocation
}
var file_delivery_service_proto_depIdxs = []int32{
	4, // 0: DeliveryDetails.destination:type_name -> DeliveryAddress
	5, // 1: DeliveryDetails.pickup:type_name -> DeliveryRestaurant
	6, // 2: DeliveryAddress.position:type_name -> DeliveryLocation
	6, // 3: DeliveryRestaurant.location:type_name -> DeliveryLocation
	3, // 4: DeliveryService.AddDelivery:input_type -> DeliveryDetails
	0, // 5: DeliveryService.GetDeliveryByOrderId:input_type -> OrderId
	2, // 6: DeliveryService.AddDelivery:output_type -> DeliverId
	1, // 7: DeliveryService.GetDeliveryByOrderId:output_type -> Delivery
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_delivery_service_proto_init() }
func file_delivery_service_proto_init() {
	if File_delivery_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_service_proto_rawDesc), len(file_delivery_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_service_proto_goTypes,
		DependencyIndexes: file_delivery_service_proto_depIdxs,
		MessageInfos:      file_delivery_service_proto_msgTypes,
	}.Build()
	File_delivery_service_proto = out.File
	file_delivery_service_proto_goTypes = nil
	file_delivery_service_proto_depIdxs = nil
}
