// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: delivery-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliverId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliverId string `protobuf:"bytes,1,opt,name=deliverId,proto3" json:"deliverId,omitempty"`
}

func (x *DeliverId) Reset() {
	*x = DeliverId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverId) ProtoMessage() {}

func (x *DeliverId) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverId.ProtoReflect.Descriptor instead.
func (*DeliverId) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverId) GetDeliverId() string {
	if x != nil {
		return x.DeliverId
	}
	return ""
}

type DeliveryDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string              `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Destination *DeliveryAddress    `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Pickup      *DeliveryRestaurant `protobuf:"bytes,3,opt,name=pickup,proto3" json:"pickup,omitempty"`
}

func (x *DeliveryDetails) Reset() {
	*x = DeliveryDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryDetails) ProtoMessage() {}

func (x *DeliveryDetails) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryDetails.ProtoReflect.Descriptor instead.
func (*DeliveryDetails) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryDetails) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeliveryDetails) GetDestination() *DeliveryAddress {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *DeliveryDetails) GetPickup() *DeliveryRestaurant {
	if x != nil {
		return x.Pickup
	}
	return nil
}

type DeliveryAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	No         string            `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Street     string            `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	Town       string            `protobuf:"bytes,3,opt,name=town,proto3" json:"town,omitempty"`
	City       string            `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode string            `protobuf:"bytes,5,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Position   *DeliveryLocation `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *DeliveryAddress) Reset() {
	*x = DeliveryAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAddress) ProtoMessage() {}

func (x *DeliveryAddress) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAddress.ProtoReflect.Descriptor instead.
func (*DeliveryAddress) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryAddress) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *DeliveryAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *DeliveryAddress) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *DeliveryAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DeliveryAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *DeliveryAddress) GetPosition() *DeliveryLocation {
	if x != nil {
		return x.Position
	}
	return nil
}

type DeliveryRestaurant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestaurantId string            `protobuf:"bytes,1,opt,name=restaurantId,proto3" json:"restaurantId,omitempty"`
	Name         string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId      string            `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Location     *DeliveryLocation `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *DeliveryRestaurant) Reset() {
	*x = DeliveryRestaurant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryRestaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRestaurant) ProtoMessage() {}

func (x *DeliveryRestaurant) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRestaurant.ProtoReflect.Descriptor instead.
func (*DeliveryRestaurant) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryRestaurant) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *DeliveryRestaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeliveryRestaurant) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DeliveryRestaurant) GetLocation() *DeliveryLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type DeliveryLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude float64 `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
}

func (x *DeliveryLocation) Reset() {
	*x = DeliveryLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryLocation) ProtoMessage() {}

func (x *DeliveryLocation) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryLocation.ProtoReflect.Descriptor instead.
func (*DeliveryLocation) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DeliveryLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

var File_delivery_service_proto protoreflect.FileDescriptor

var file_delivery_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x32, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x06, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x69, 0x63, 0x6b,
	0x75, 0x70, 0x22, 0xb0, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f,
	0x77, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4c, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x32, 0x40, 0x0a, 0x0f, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d,
	0x0a, 0x0b, 0x41, 0x64, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x10, 0x2e,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a,
	0x0a, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x00, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_service_proto_rawDescOnce sync.Once
	file_delivery_service_proto_rawDescData = file_delivery_service_proto_rawDesc
)

func file_delivery_service_proto_rawDescGZIP() []byte {
	file_delivery_service_proto_rawDescOnce.Do(func() {
		file_delivery_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_service_proto_rawDescData)
	})
	return file_delivery_service_proto_rawDescData
}

var file_delivery_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_delivery_service_proto_goTypes = []interface{}{
	(*DeliverId)(nil),          // 0: DeliverId
	(*DeliveryDetails)(nil),    // 1: DeliveryDetails
	(*DeliveryAddress)(nil),    // 2: DeliveryAddress
	(*DeliveryRestaurant)(nil), // 3: DeliveryRestaurant
	(*DeliveryLocation)(nil),   // 4: DeliveryLocation
}
var file_delivery_service_proto_depIdxs = []int32{
	2, // 0: DeliveryDetails.destination:type_name -> DeliveryAddress
	3, // 1: DeliveryDetails.pickup:type_name -> DeliveryRestaurant
	4, // 2: DeliveryAddress.position:type_name -> DeliveryLocation
	4, // 3: DeliveryRestaurant.location:type_name -> DeliveryLocation
	1, // 4: DeliveryService.AddDelivery:input_type -> DeliveryDetails
	0, // 5: DeliveryService.AddDelivery:output_type -> DeliverId
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_delivery_service_proto_init() }
func file_delivery_service_proto_init() {
	if File_delivery_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delivery_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryRestaurant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_service_proto_goTypes,
		DependencyIndexes: file_delivery_service_proto_depIdxs,
		MessageInfos:      file_delivery_service_proto_msgTypes,
	}.Build()
	File_delivery_service_proto = out.File
	file_delivery_service_proto_rawDesc = nil
	file_delivery_service_proto_goTypes = nil
	file_delivery_service_proto_depIdxs = nil
}
